const baseWorldMonsters = [
    {name:"Great Jagras", species:"Fanged Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Great_Jagras_Icon.png"},
    {name:"Kulu-Ya-Ku", species:"Bird Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Kulu-Ya-Ku_Icon.png"},
    {name:"Pukei-Pukei", species:"Bird Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Pukei-Pukei_Icon.png"},
    {name:"Barroth", species:"Brute Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Barroth_Icon.png"},
    {name:"Jyuratodus", species:"Fish Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Jyuratodus_Icon.png"},
    {name:"Tobi-Kadachi", species:"Fanged Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Tobi-Kadachi_Icon.png"},
    {name:"Rathian", species:"Flying Wyverns", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Rathian_Icon.png"},
    {name:"Anjanath", species:"Brute Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Anjanath_Icon.png"},
    {name:"Tzitzi-Ya-Ku", species:"Bird Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Tzitzi-Ya-Ku_Icon.png"},
    {name:"Paolumu", species:"Bird Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Paolumu_Icon.png"},
    {name:"Great Girros", species:"Fanged Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Great_Girros_Icon.png"},
    {name:"Radobaan", species:"Brute Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Radobaan_Icon.png"},
    {name:"Legiana", species:"Flying Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Legiana_Icon.png"},
    {name:"Odogaron", species:"Brute Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Odogaron_Icon.png"},
    {name:"Rathalos", species:"Flying Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Rathalos_Icon.png"},
    {name:"Diablos", species:"Flying Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Diablos_Icon.png"},
    {name:"Zorah Magdaros", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Zorah_Magdaros_Icon.png"},
    {name:"Pink Rathian", species:"Flying Wyverns", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Pink_Rathian_Icon.png"},
    {name:"Nergigante", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Nergigante_Icon.png"},
    {name:"Kushala Daora", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Kushala_Daora_Icon.png"},
    {name:"Teostra", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Teostra_Icon.png"},
    {name:"Vaal Hazak", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Vaal_Hazak_Icon.png"},
    {name:"Xeno'Jiiva", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Xeno'Jiiva_Icon.png"},
    {name:"Bazelgeuse", species:"Flying Wyverns", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Bazelgeuse_Icon.png"},
    {name:"Kirin", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Kirin_Icon.png"},
    {name:"Dodogama", species:"Brute Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Dodogama_Icon.png"},
    {name:"Azure Rathalos", species:"Flying Wyverns", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Azure_Rathalos_Icon.png"},
    {name:"Lavasioth", species:"Piscine Wyverns", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Lavasioth_Icon.png"},
    {name:"Uragaan", species:"Brute Wyverns", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Uragaan_Icon.png"},
    {name:"Black Diablos", species:"Flying Wyverns", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Black_Diablos_Icon.png"},
    {name:"Deviljho", species:"Brute Wyverns", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Deviljho_Icon.png"},
    {name:"Kulve Taroth", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Kulve_Taroth_Icon.png"},
    {name:"Lunastra", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Lunastra_Icon.png"},
    {name:"Behemoth", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Behemoth_Icon.png"},
    {name:"Leshen", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Leshen_Icon.png"},
    {name:"Ancient Leshen", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Ancient_Leshen_Icon.png"},
    {name:"Jagras", species:"Fanged Wyverns", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Jagras_Icon.png"},
    {name:"Kelbi", species:"Herbivores", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Kelbi_Icon.png"},
    {name:"Hornetaur", species:"Neopterons", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Hornetaur_Icon.png"},
    {name:"Kestodon-Male", species:"Herbivores", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Kestodon_Male_Icon.png"},
    {name:"Kestodon-Female", species:"Herbivores", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Kestodon_Female_Icon.png"},
    {name:"Girros", species:"Fanged Wyverns", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Girros_Icon.png"},
    {name:"Mernos", species:"Wingdrakes", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Mernos_Icon.png"},
    {name:"Gastodon", species:"Herbivores", rank:"High-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Gastodon_Icon.png"},
    {name:"Mosswine", species:"Herbivores", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Mosswine_Icon.png"},
    {name:"Gajau", species:"Fish", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Gajau_Icon.png"},
    {name:"Noios", species:"Wingdrakes", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Noios_Icon.png"},
    {name:"Gajalaka", species:"Lynians", rank:"High-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Gajalaka_Icon.png"},
    {name:"Raphinos", species:"Wingdrakes", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Raphinos_Icon.png"},
    {name:"Barnos", species:"Wingdrakes", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Barnos_Icon.png"},
    {name:"Shamos", species:"Fanged Wyverns", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Shamos_Icon.png"},
    {name:"Aptonoth", species:"Herbivores", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Aptonoth_Icon.png"},
    {name:"Vespoid", species:"Neopterons", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Vespoid_Icon.png"},
    {name:"Apceros", species:"Herbivores", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Apceros_Icon.png"}
    
];

const baseLargeMonsters = [
    {name:"Great Jagras", species:"Fanged Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Great_Jagras_Icon.png"},
    {name:"Kulu-Ya-Ku", species:"Bird Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Kulu-Ya-Ku_Icon.png"},
    {name:"Pukei-Pukei", species:"Bird Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Pukei-Pukei_Icon.png"},
    {name:"Barroth", species:"Brute Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Barroth_Icon.png"},
    {name:"Jyuratodus", species:"Fish Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Jyuratodus_Icon.png"},
    {name:"Tobi-Kadachi", species:"Fanged Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Tobi-Kadachi_Icon.png"},
    {name:"Rathian", species:"Flying Wyverns", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Rathian_Icon.png"},
    {name:"Anjanath", species:"Brute Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Anjanath_Icon.png"},
    {name:"Tzitzi-Ya-Ku", species:"Bird Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Tzitzi-Ya-Ku_Icon.png"},
    {name:"Paolumu", species:"Bird Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Paolumu_Icon.png"},
    {name:"Great Girros", species:"Fanged Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Great_Girros_Icon.png"},
    {name:"Radobaan", species:"Brute Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Radobaan_Icon.png"},
    {name:"Legiana", species:"Flying Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Legiana_Icon.png"},
    {name:"Odogaron", species:"Brute Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Odogaron_Icon.png"},
    {name:"Rathalos", species:"Flying Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Rathalos_Icon.png"},
    {name:"Diablos", species:"Flying Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Diablos_Icon.png"},
    {name:"Zorah Magdaros", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Zorah_Magdaros_Icon.png"},
    {name:"Pink Rathian", species:"Flying Wyverns", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Pink_Rathian_Icon.png"},
    {name:"Nergigante", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Nergigante_Icon.png"},
    {name:"Kushala Daora", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Kushala_Daora_Icon.png"},
    {name:"Teostra", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Teostra_Icon.png"},
    {name:"Vaal Hazak", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Vaal_Hazak_Icon.png"},
    {name:"Xeno'Jiiva", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Xeno'Jiiva_Icon.png"},
    {name:"Bazelgeuse", species:"Flying Wyverns", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Bazelgeuse_Icon.png"},
    {name:"Kirin", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Kirin_Icon.png"},
    {name:"Dodogama", species:"Brute Wyverns", rank:"Low-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Dodogama_Icon.png"},
    {name:"Azure Rathalos", species:"Flying Wyverns", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Azure_Rathalos_Icon.png"},
    {name:"Lavasioth", species:"Piscine Wyverns", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Lavasioth_Icon.png"},
    {name:"Uragaan", species:"Brute Wyverns", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Uragaan_Icon.png"},
    {name:"Black Diablos", species:"Flying Wyverns", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Black_Diablos_Icon.png"},
    {name:"Deviljho", species:"Brute Wyverns", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Deviljho_Icon.png"},
    {name:"Kulve Taroth", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Kulve_Taroth_Icon.png"},
    {name:"Lunastra", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Lunastra_Icon.png"},
    {name:"Behemoth", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Behemoth_Icon.png"},
    {name:"Leshen", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Leshen_Icon.png"},
    {name:"Ancient Leshen", species:"Elder Dragons", rank:"High-Rank",image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/LargeMonsters-Icons/MHWI-Ancient_Leshen_Icon.png"}
];

const baseSmallMonsters = [
    {name:"Jagras", species:"Fanged Wyverns", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Jagras_Icon.png"},
    {name:"Kelbi", species:"Herbivores", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Kelbi_Icon.png"},
    {name:"Hornetaur", species:"Neopterons", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Hornetaur_Icon.png"},
    {name:"Kestodon-Male", species:"Herbivores", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Kestodon_Male_Icon.png"},
    {name:"Kestodon-Female", species:"Herbivores", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Kestodon_Female_Icon.png"},
    {name:"Girros", species:"Fanged Wyverns", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Girros_Icon.png"},
    {name:"Mernos", species:"Wingdrakes", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Mernos_Icon.png"},
    {name:"Gastodon", species:"Herbivores", rank:"High-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Gastodon_Icon.png"},
    {name:"Mosswine", species:"Herbivores", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Mosswine_Icon.png"},
    {name:"Gajau", species:"Fish", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Gajau_Icon.png"},
    {name:"Noios", species:"Wingdrakes", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Noios_Icon.png"},
    {name:"Gajalaka", species:"Lynians", rank:"High-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Gajalaka_Icon.png"},
    {name:"Raphinos", species:"Wingdrakes", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Raphinos_Icon.png"},
    {name:"Barnos", species:"Wingdrakes", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Barnos_Icon.png"},
    {name:"Shamos", species:"Fanged Wyverns", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Shamos_Icon.png"},
    {name:"Aptonoth", species:"Herbivores", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Aptonoth_Icon.png"},
    {name:"Vespoid", species:"Neopterons", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Vespoid_Icon.png"},
    {name:"Apceros", species:"Herbivores", rank:"Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld/SmallMonsters-Icon/MHWI-Apceros_Icon.png"}
];

const expansionIceborneMonsters = [
    {name:"Beotodus", species:"Piscine Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Beotodus_Icon.png"},
    {name:"Banbaro", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Banbaro_Icon.png"},
    {name:"Viper Tobi-Kadachi", species:"Fanged Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Viper_Tobi-Kadachi_Icon.png"},
    {name:"Nightshade Paolumu", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Nightshade_Paolumu_Icon.png"},
    {name:"Coral Pukei-Pukei", species:"Piscine Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Coral_Pukei-Pukei_Icon.png"},
    {name:"Barioth", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Barioth_Icon.png"},
    {name:"Nargacuga", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Nargacuga_Icon.png"},
    {name:"Glavenus", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Glavenus_Icon.png"},
    {name:"Tigrex", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Tigrex_Icon.png"},
    {name:"Brachydios", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Brachydios_Icon.png"},
    {name:"Shrieking Legiana", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Shrieking_Legiana_Icon.png"},
    {name:"Acidic Glavenus", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Acidic_Glavenus_Icon.png"},
    {name:"Ebony Odogaron", species:"Fanged Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Ebony_Odogaron_Icon.png"},
    {name:"Fulgur Anjanath", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Fulgur_Anjanath_Icon.png"},
    {name:"Velkhana", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Velkhana_Icon.png"},
    {name:"Seething Bazelgeuse", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Seething_Bazelgeuse_Icon.png"},
    {name:"Blackveil Vaal Hazak", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Blackveil_Vaal_Hazak_Icon.png"},
    {name:"Namielle", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Namielle_Icon.png"},
    {name:"Ruiner Negigante", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Ruiner_Nergigante_Icon.png"},
    {name:"Shara Ishvalda", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Shara_Ishvalda_Icon.png"},
    {name:"Yian Garuga", species:"Bird Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Yian_Garuga_Icon.png"},
    {name:"Scarred Yian Garuga", species:"Bird Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Scarred_Yian_Garuga_Icon.png"},
    {name:"Rajang", species:"Fanged Beasts", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Rajang_Icon.png"},
    {name:"Furious Rajang", species:"Fanged Beasts", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Furious_Rajang_Icon.png"},
    {name:"Raging Brachydios", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Raging_Brachydios_Icon.png"},
    {name:"Zinogre", species:"Fanged Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Zinogre_Icon.png"},
    {name:"Brute Tigrex", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Brute_Tigrex_Icon.png"},
    {name:"Gold Rathian", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Gold_Rathian_Icon.png"},
    {name:"Silver Rathalos", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Silver_Rathalos_Icon.png"},
    {name:"Stygian Zinogre", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Stygian_Zinogre_Icon.png"},
    {name:"Savage Deviljho", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Savage_Deviljho_Icon.png"},
    {name:"Frostfang Barioth", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Frostfang_Barioth_Icon.webp"},
    {name:"Safi'jiiva", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Safi'jiiva_Icon.png"},
    {name:"Alatreon", species:"Black Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Alatreon_Icon.png"},
    {name:"Fatalis", species:"Black Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Fatalis_Icon.png"},
    {name:"Cortos", species:"Wingdrakes", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/SmallMonsters-Icon/MHWI-Cortos_Icon.png"},
    {name:"Popo", species:"Herbivores", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/SmallMonsters-Icon/MHWI-Popo_Icon.png"},
    {name:"Boaboa", species:"Lynians", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/SmallMonsters-Icon/MHWI-Boaboa_Icon.png"},
    {name:"Wulg", species:"Fanged Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/SmallMonsters-Icon/MHWI-Wulg_Icon.png"},
    {name:"Anteka", species:"Herbivores", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/SmallMonsters-Icon/120px-MHWI-Anteka_Icon.png.webp"}
    
];
const expansionLargeMonsters = [
    {name:"Beotodus", species:"Piscine Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Beotodus_Icon.png"},
    {name:"Banbaro", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Banbaro_Icon.png"},
    {name:"Viper Tobi-Kadachi", species:"Fanged Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Viper_Tobi-Kadachi_Icon.png"},
    {name:"Nightshade Paolumu", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Nightshade_Paolumu_Icon.png"},
    {name:"Coral Pukei-Pukei", species:"Piscine Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Coral_Pukei-Pukei_Icon.png"},
    {name:"Barioth", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Barioth_Icon.png"},
    {name:"Nargacuga", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Nargacuga_Icon.png"},
    {name:"Glavenus", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Glavenus_Icon.png"},
    {name:"Tigrex", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Tigrex_Icon.png"},
    {name:"Brachydios", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Brachydios_Icon.png"},
    {name:"Shrieking Legiana", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Shrieking_Legiana_Icon.png"},
    {name:"Acidic Glavenus", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Acidic_Glavenus_Icon.png"},
    {name:"Ebony Odogaron", species:"Fanged Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Ebony_Odogaron_Icon.png"},
    {name:"Fulgur Anjanath", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Fulgur_Anjanath_Icon.png"},
    {name:"Velkhana", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Velkhana_Icon.png"},
    {name:"Seething Bazelgeuse", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Seething_Bazelgeuse_Icon.png"},
    {name:"Blackveil Vaal Hazak", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Blackveil_Vaal_Hazak_Icon.png"},
    {name:"Namielle", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Namielle_Icon.png"},
    {name:"Ruiner Negigante", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Ruiner_Nergigante_Icon.png"},
    {name:"Shara Ishvalda", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Shara_Ishvalda_Icon.png"},
    {name:"Yian Garuga", species:"Bird Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Yian_Garuga_Icon.png"},
    {name:"Scarred Yian Garuga", species:"Bird Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Scarred_Yian_Garuga_Icon.png"},
    {name:"Rajang", species:"Fanged Beasts", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Rajang_Icon.png"},
    {name:"Furious Rajang", species:"Fanged Beasts", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Furious_Rajang_Icon.png"},
    {name:"Raging Brachydios", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Raging_Brachydios_Icon.png"},
    {name:"Zinogre", species:"Fanged Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Zinogre_Icon.png"},
    {name:"Brute Tigrex", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Brute_Tigrex_Icon.png"},
    {name:"Gold Rathian", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Gold_Rathian_Icon.png"},
    {name:"Silver Rathalos", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Silver_Rathalos_Icon.png"},
    {name:"Stygian Zinogre", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Stygian_Zinogre_Icon.png"},
    {name:"Savage Deviljho", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Savage_Deviljho_Icon.png"},
    {name:"Frostfang Barioth", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Frostfang_Barioth_Icon.webp"},
    {name:"Safi'jiiva", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Safi'jiiva_Icon.png"},
    {name:"Alatreon", species:"Black Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Alatreon_Icon.png"},
    {name:"Fatalis", species:"Black Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/LargeMonsters-Icon/MHWI-Fatalis_Icon.png"},
];
const expansionSmallMonsters = [
    {name:"Cortos", species:"Wingdrakes", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/SmallMonsters-Icon/MHWI-Cortos_Icon.png"},
    {name:"Popo", species:"Herbivores", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/SmallMonsters-Icon/MHWI-Popo_Icon.png"},
    {name:"Boaboa", species:"Lynians", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/SmallMonsters-Icon/MHWI-Boaboa_Icon.png"},
    {name:"Wulg", species:"Fanged Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/SmallMonsters-Icon/MHWI-Wulg_Icon.png"},
    {name:"Anteka", species:"Herbivores", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWorld-Iceborne/SmallMonsters-Icon/120px-MHWI-Anteka_Icon.png.webp"}
];