const baseWildsMonsters = [
    {id: 1, name: "Chatacabra", species: "Amphibians", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Chatacabra_Icon.webp"},
    {id: 2, name: "Quematrice", species: "Brute Wyverns", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Quematrice_Icon.webp"},
    {id: 3, name: "Lala Barina", species: "Temnocerans", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Lala_Barina_Icon.webp"},
    {id: 4, name: "Congalala", species: "Fanged Beasts", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Congalala_Icon.webp"},
    {id: 5, name: "Balahara", species: "Leviathans", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Balahara_Icon.webp"},
    {id: 6, name: "Doshaguma", species: "Fanged Beasts", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Doshaguma_Icon.webp"},
    {id: 7, name: "Uth Duna", species: "Leviathans", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Uth_Duna_Icon.webp"},
    {id: 8, name: "Rompopolo", species: "Brute Wyverns", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Rompopolo_Icon.webp"},
    {id: 9, name: "Rey Dau", species: "Flying Wyverns", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Rey_Dau_Icon.webp"},
    {id: 10, name: "Nerscylla", species: "Temnocerans", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Nerscylla_Icon.webp"},
    {id: 11, name: "Hirabami", species: "Leviathans", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Hirabami_Icon.webp"},
    {id: 12, name: "Ajarakan", species: "Fanged Beasts", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Ajarakan_Icon.webp"},
    {id: 13, name: "Nu Udra", species: "Cephalopods", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Nu_Udra_Icon.webp"},
    {id: 14, name: "Guardian Doshaguma", species: "Constructs", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Guardian_Doshaguma_Icon.webp"},
    {id: 15, name: "Guardian Rathalos", species: "Constructs", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Guardian_Rathalos_Icon.webp"},
    {id: 16, name: "Guardian Ebony Odogaron", species: "Constructs", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Guardian_Ebony_Odogaron_Icon.webp"},
    {id: 17, name: "Xu Wu", species: "Cephalopods", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Xu_Wu_Icon.webp"},
    {id: 18, name: "Guardian Arkveld", species: "Constructs", rank: "Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Guardian_Arkveld_Icon.webp"},
    {id: 19, name: "Zoh Shia", species: "Constructs", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Zoh_Shia_Icon.webp"},
    {id: 20, name: "Yian Kut-Ku", species: "Bird Wyverns", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Yian_Kut-Ku_Icon.webp"},
    {id: 21, name: "Rathian", species: "Flying Wyverns", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Rathian_Icon.webp"},
    {id: 22, name: "Gypceros", species: "Bird Wyverns", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Gypceros_Icon.webp"},
    {id: 23, name: "Blangonga", species: "Fanged Beasts", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Blangonga_Icon.webp"},
    {id: 24, name: "Rathalos", species: "Flying Wyverns", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Rathalos_Icon.webp"},
    {id: 25, name: "Guardian Fulgur Anjanath", species: "Brute Wyverns", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Guardian_Fulgur_Anjanath_Icon.webp"},
    {id: 26, name: "Gravios", species: "Flying Wyverns", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Gravios_Icon.webp"},
    {id: 27, name: "Jin Dahaad", species: "Leviathans", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Jin_Dahaad_Icon.webp"},
    {id: 28, name: "Gore Magala", species: "Demi Elder", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Gore_Magala_Icon.webp"},
    {id: 29, name: "Arkveld", species: "Flying Wyverns", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Arkveld_Icon.webp"},
    {id: 30, name: "Mizutsune", species: "Leviathans", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Mizutsune_Icon.webp"},
    {id: 31, name: "Lagiacrus", species: "Leviathans", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Lagiacrus_Icon.webp"},
    {id: 32, name: "Seregios", species: "Flying Wyverns", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Seregios_Icon.webp"},
    {id: 33, name: "Omega Planetes", species: "???", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Omega_Planetes_Icon.webp"},
    {id: 34, name: "Gogmazios", species: "Elder Dragons", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Gogmazios_Icon.webp"},
    {id: 35, name: "Baunos", species: "Wingdrakes", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Baunos_Icon.webp"},
    {id: 36, name: "Blango", species: "Fanged Beasts", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Blango_Icon.webp"},
    {id: 37, name: "Bulaqchi", species: "Neopterons", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Bulaqchi_Icon.webp"},
    {id: 38, name: "Ceratonoth", species: "Herbivores", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Ceratonoth_Icon.webp"},
    {id: 39, name: "Ceratonoth Female", species: "Herbivores", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Ceratonoth_Female_Icon.png"},
    {id: 40, name: "Comaqchi", species: "Neopterons", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Comaqchi_Icon.webp"},
    {id: 41, name: "Conga", species: "Fanged Beasts", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Conga_Icon.webp"},
    {id: 42, name: "Dalthydon", species: "Herbivores", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Dalthydon_Icon.webp"},
    {id: 43, name: "Gajios", species: "Leviathans", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Gajios_Icon.webp"},
    {id: 44, name: "Gelidron", species: "Amphibians", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Gelidron_Icon.webp"},
    {id: 45, name: "Guardian Seikret", species: "Constructs", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Guardian_Seikret_Icon.webp"},
    {id: 46, name: "Harpios", species: "Wingdrakes", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Harpios_Icon.webp"},
    {id: 47, name: "Kranodath", species: "Bird Wyverns", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Kranodath_Icon.webp"},
    {id: 48, name: "Nerscylla Hatchling", species: "Temnocerans", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Nerscylla_Hatchling_Icon.webp"},
    {id: 49, name: "Omega Micros", species: "???", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Omega_Micros_Icon.webp"},
    {id: 50, name: "Piragill", species: "Leviathans", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Piragill_Icon.webp"},
    {id: 51, name: "Porkeplume", species: "Bird Wyverns", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Porkeplume_Icon.webp"},
    {id: 52, name: "Rafma", species: "Herbivores", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Rafma_Icon.webp"},
    {id: 53, name: "Talioth", species: "Bird Wyverns", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Talioth_Icon.webp"},
    {id: 54, name: "Vespoid", species: "Neopterons", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Vespoid_Icon.webp"}
];

const baseLargeMonsters = [
    {id: 1, name: "Chatacabra", species: "Amphibians", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Chatacabra_Icon.webp"},
    {id: 2, name: "Quematrice", species: "Brute Wyverns", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Quematrice_Icon.webp"},
    {id: 3, name: "Lala Barina", species: "Temnocerans", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Lala_Barina_Icon.webp"},
    {id: 4, name: "Congalala", species: "Fanged Beasts", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Congalala_Icon.webp"},
    {id: 5, name: "Balahara", species: "Leviathans", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Balahara_Icon.webp"},
    {id: 6, name: "Doshaguma", species: "Fanged Beasts", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Doshaguma_Icon.webp"},
    {id: 7, name: "Uth Duna", species: "Leviathans", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Uth_Duna_Icon.webp"},
    {id: 8, name: "Rompopolo", species: "Brute Wyverns", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Rompopolo_Icon.webp"},
    {id: 9, name: "Rey Dau", species: "Flying Wyverns", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Rey_Dau_Icon.webp"},
    {id: 10, name: "Nerscylla", species: "Temnocerans", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Nerscylla_Icon.webp"},
    {id: 11, name: "Hirabami", species: "Leviathans", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Hirabami_Icon.webp"},
    {id: 12, name: "Ajarakan", species: "Fanged Beasts", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Ajarakan_Icon.webp"},
    {id: 13, name: "Nu Udra", species: "Cephalopods", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Nu_Udra_Icon.webp"},
    {id: 14, name: "Guardian Doshaguma", species: "Constructs", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Guardian_Doshaguma_Icon.webp"},
    {id: 15, name: "Guardian Rathalos", species: "Constructs", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Guardian_Rathalos_Icon.webp"},
    {id: 16, name: "Guardian Ebony Odogaron", species: "Constructs", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Guardian_Ebony_Odogaron_Icon.webp"},
    {id: 17, name: "Xu Wu", species: "Cephalopods", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Xu_Wu_Icon.webp"},
    {id: 18, name: "Guardian Arkveld", species: "Constructs", rank: "Low-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Guardian_Arkveld_Icon.webp"},
    {id: 19, name: "Zoh Shia", species: "Constructs", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Zoh_Shia_Icon.webp"},
    {id: 20, name: "Yian Kut-Ku", species: "Bird Wyverns", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Yian_Kut-Ku_Icon.webp"},
    {id: 21, name: "Rathian", species: "Flying Wyverns", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Rathian_Icon.webp"},
    {id: 22, name: "Gypceros", species: "Flying Wyverns", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Gypceros_Icon.webp"},
    {id: 23, name: "Blangonga", species: "Fanged Beasts", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Blangonga_Icon.webp"},
    {id: 24, name: "Rathalos", species: "Flying Wyverns", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Rathalos_Icon.webp"},
    {id: 25, name: "Guardian Fulgur Anjanath", species: "Brute Wyverns", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Guardian_Fulgur_Anjanath_Icon.webp"},
    {id: 26, name: "Gravios", species: "Flying Wyverns", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Gravios_Icon.webp"},
    {id: 27, name: "Jin Dahaad", species: "Leviathans", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Jin_Dahaad_Icon.webp"},
    {id: 28, name: "Gore Magala", species: "Demi Elder", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Gore_Magala_Icon.webp"},
    {id: 29, name: "Arkveld", species: "Flying Wyverns", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Arkveld_Icon.webp"},
    {id: 30, name: "Mizutsune", species: "Leviathans", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Mizutsune_Icon.webp"},
    {id: 31, name: "Lagiacrus", species: "Leviathans", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Lagiacrus_Icon.webp"},
    {id: 32, name: "Seregios", species: "Flying Wyverns", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Seregios_Icon.webp"},
    {id: 33, name: "Omega Planetes", species: "???", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Omega_Planetes_Icon.webp"},
    {id: 34, name: "Gogmazios", species: "Elder Dragons", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/LargeMonsters-Icon/MHWilds-Gogmazios_Icon.webp"}
];

const baseSmallMonsters = [
    {id: 35, name: "Baunos", species: "Wingdrakes", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Baunos_Icon.webp"},
    {id: 36, name: "Blango", species: "Fanged Beasts", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Blango_Icon.webp"},
    {id: 37, name: "Bulaqchi", species: "Neopterons", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Bulaqchi_Icon.webp"},
    {id: 38, name: "Ceratonoth", species: "Herbivores", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Ceratonoth_Icon.webp"},
    {id: 39, name: "Ceratonoth Female", species: "Herbivores", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Ceratonoth_Female_Icon.png"},
    {id: 40, name: "Comaqchi", species: "Neopterons", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Comaqchi_Icon.webp"},
    {id: 41, name: "Conga", species: "Fanged Beasts", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Conga_Icon.webp"},
    {id: 42, name: "Dalthydon", species: "Herbivores", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Dalthydon_Icon.webp"},
    {id: 43, name: "Gajios", species: "Leviathans", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Gajios_Icon.webp"},
    {id: 44, name: "Gelidron", species: "Amphibians", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Gelidron_Icon.webp"},
    {id: 45, name: "Guardian Seikret", species: "Constructs", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Guardian_Seikret_Icon.webp"},
    {id: 46, name: "Harpios", species: "Wingdrakes", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Harpios_Icon.webp"},
    {id: 47, name: "Kranodath", species: "Bird Wyverns", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Kranodath_Icon.webp"},
    {id: 48, name: "Nerscylla Hatchling", species: "Temnocerans", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Nerscylla_Hatchling_Icon.webp"},
    {id: 49, name: "Omega Micros", species: "???", rank: "High-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Omega_Micros_Icon.webp"},
    {id: 50, name: "Piragill", species: "Leviathans", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Piragill_Icon.webp"},
    {id: 51, name: "Porkeplume", species: "Bird Wyverns", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Porkeplume_Icon.webp"},
    {id: 52, name: "Rafma", species: "Herbivores", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Rafma_Icon.webp"},
    {id: 53, name: "Talioth", species: "Bird Wyverns", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Talioth_Icon.webp"},
    {id: 54, name: "Vespoid", species: "Neopterons", rank: "Low-Rank", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterWilds/SmallMonsters-Icon/MHWilds-Vespoid_Icon.webp"}
];

const expansionWildsMonsters = [{}];
const expansionLargeMonsters = [{}];
const expansionSmallMonsters = [{}];