const baseRiseMonsters = [
    {id: 1, name:"Great Izuchi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Great_Izuchi_Icon.png"},
    {id: 2, name:"Great Baggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Great_Baggi_Icon.png"},
    {id: 3, name:"Kulu-Ya-Ku", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Kulu-Ya-Ku_Icon.png"},
    {id: 4, name:"Great Wroggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Great_Wroggi_Icon.png"},
    {id: 5, name:"Arzuros", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Arzuros_Icon.png"},
    {id: 6, name:"Lagombi", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Lagombi_Icon.png"},
    {id: 7, name:"Volvidon", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Volvidon_Icon.png"},
    {id: 8, name:"Aknosom", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Aknosom_Icon.png"},
    {id: 9, name:"Royal Ludroth", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Royal_Ludroth_Icon.png"},
    {id: 10, name:"Barroth", species: "Brute Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Barroth_Icon.png"},
    {id: 11, name:"Khezu", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Khezu_Icon.png"},
    {id: 12, name:"Tetranadon", species: "Amphibians", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Tetranadon_Icon.png"},
    {id: 13, name:"Bishaten", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Bishaten_Icon.png"},
    {id: 14, name:"Pukei-Pukei", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Pukei-Pukei_Icon.png"},
    {id: 15, name:"Basarios", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Basarios_Icon.png"},
    {id: 16, name:"Somnacanth", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Somnacanth_Icon.png"},
    {id: 17, name:"Rathian", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Rathian_Icon.png"},
    {id: 18, name:"Barioth", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Barioth_Icon.png"},
    {id: 19, name:"Tobi-Kadachi", species: "Fanged Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Tobi-Kadachi_Icon.png"},
    {id: 20, name:"Magnamalo", species: "Brute Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Magnamalo_Icon.png"},
    {id: 21, name:"Anjanath", species: "Brute Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Anjanath_Icon.png"},
    {id: 22, name:"Mizutsune", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Mizutsune_Icon.png"},
    {id: 23, name:"Almudron", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Almudron_Icon.png"},
    {id: 24, name:"Goss Harag", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Goss_Harag_Icon.png"},
    {id: 25, name:"Tigrex", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Tigrex_Icon.png"},
    {id: 26, name:"Zinogre", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Zinogre_Icon.png"},
    {id: 27, name:"Diablos", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Diablos_Icon.png"},
    {id: 28, name:"Rathalos", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Rathalos_Icon.png"},
    {id: 29, name:"Nargacuga", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Nargacuga_Icon.png"},
    {id: 30, name:"Rakna-Kadaki", species: "Temnocerans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Rakna-Kadaki_Icon.png"},
    {id: 31, name:"Rajang", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Rajang_Icon.png"},
    {id: 32, name:"Jyuratodus", species: "Piscine Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Jyuratodus_Icon.png"},
    {id: 33, name:"Bazelgeuse", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Bazelgeuse_Icon.png"},
    {id: 34, name:"Kushala Daora", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Kushala_Daora_Icon.png"},
    {id: 35, name:"Teostra", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Teostra_Icon.png"},
    {id: 36, name:"Chameleos", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Chameleos_Icon.png"},
    {id: 37, name:"Crimson Glow Valstrax", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Crimson_Glow_Valstrax_Icon.png"},
    {id: 38, name:"Thunder Serpent Narwa", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Thunder_Serpent_Narwa_Icon.png"},
    {id: 39, name:"Wind Serpent Ibushi", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Wind_Serpent_Ibushi_Icon.png"},
    {id: 40, name:"Narwa the Allmother", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Narwa_the_Allmother_Icon.png"},
    {id: 41, name:"Apex Rathalos", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Rathalos_Icon.png"},
    {id: 42, name:"Apex Rathian", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Rathian_Icon.png"},
    {id: 43, name:"Apex Diablos", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Diablos_Icon.png"},
    {id: 44, name:"Apex Arzuros", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Arzuros_Icon.png"},
    {id: 45, name:"Apex Zinogre", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Zinogre_Icon.png"},
    {id: 46, name:"Apex Mizutsune", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Mizutsune_Icon.png"},
    
    {id: 47, name:"Izuchi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Izuchi_Icon.png"},
    {id: 48, name:"Baggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Baggi_Icon.png"},
    {id: 49, name:"Wroggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Wroggi_Icon.png"},
    {id: 50, name:"Jaggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Jaggi_Icon.png"},
    {id: 51, name:"Jaggia", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Jaggia_Icon.png"},
    {id: 52, name:"Gajau", species: "Fish", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Gajau_Icon.png"},
    {id: 53, name:"Anteka", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Anteka_Icon.png"},
    {id: 54, name:"Kelbi", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Kelbi_Icon.png"},
    {id: 55, name:"Popo", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Popo_Icon.png"},
    {id: 56, name:"Rhenoplos", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Rhenoplos_Icon.png"},
    {id: 57, name:"Kestodon Male", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Kestodon_Male_Icon.png"},
    {id: 58, name:"Kestodon Female", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Kestodon_Female_Icon.png"},
    {id: 59, name:"Slagtoth", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Slagtoth_Icon.png"},
    {id: 60, name:"Melynx", species: "Lynians", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Melynx_Icon.png"},
    {id: 61, name:"Felyne", species: "Lynians", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Felyne_Icon.png"},
    {id: 62, name:"Altaroth", species: "Neopterons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Altaroth_Icon.png"},
    {id: 63, name:"Bnahabra", species: "Neopterons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Bnahabra_Icon.png"},
    {id: 64, name:"Rachnoid", species: "Temnocerans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Rachnoid_Icon.png"},
    {id: 65, name:"Zamite", species: "Amphibians", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Zamite_Icon.png"},
    {id: 66, name:"Bombadgy", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Bombadgy_Icon.png"},
    {id: 67, name:"Ludroth", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Ludroth_Icon.png"},
    {id: 68, name:"Delex", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Delex_Icon.png"},
    {id: 69, name:"Bullfango", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Bullfango_Icon.png"},
    {id: 70, name:"Jagras", species: "Fanged Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Jagras_Icon.png"},
    {id: 71, name:"Gargwa", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Gargwa_Icon.png"},
    {id: 72, name:"Remobra", species: "Snake Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Remobra_Icon.png"},
    {id: 73, name:"Uroktor", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Uroktor_Icon.png"}
];

const baseLargeMonsters = [
    {id: 1, name:"Great Izuchi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Great_Izuchi_Icon.png"},
    {id: 2, name:"Great Baggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Great_Baggi_Icon.png"},
    {id: 3, name:"Kulu-Ya-Ku", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Kulu-Ya-Ku_Icon.png"},
    {id: 4, name:"Great Wroggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Great_Wroggi_Icon.png"},
    {id: 5, name:"Arzuros", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Arzuros_Icon.png"},
    {id: 6, name:"Lagombi", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Lagombi_Icon.png"},
    {id: 7, name:"Volvidon", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Volvidon_Icon.png"},
    {id: 8, name:"Aknosom", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Aknosom_Icon.png"},
    {id: 9, name:"Royal Ludroth", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Royal_Ludroth_Icon.png"},
    {id: 10, name:"Barroth", species: "Brute Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Barroth_Icon.png"},
    {id: 11, name:"Khezu", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Khezu_Icon.png"},
    {id: 12, name:"Tetranadon", species: "Amphibians", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Tetranadon_Icon.png"},
    {id: 13, name:"Bishaten", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Bishaten_Icon.png"},
    {id: 14, name:"Pukei-Pukei", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Pukei-Pukei_Icon.png"},
    {id: 15, name:"Basarios", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Basarios_Icon.png"},
    {id: 16, name:"Somnacanth", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Somnacanth_Icon.png"},
    {id: 17, name:"Rathian", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Rathian_Icon.png"},
    {id: 18, name:"Barioth", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Barioth_Icon.png"},
    {id: 19, name:"Tobi-Kadachi", species: "Fanged Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Tobi-Kadachi_Icon.png"},
    {id: 20, name:"Magnamalo", species: "Fanged Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Magnamalo_Icon.png"},
    {id: 21, name:"Anjanath", species: "Brute Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Anjanath_Icon.png"},
    {id: 22, name:"Mizutsune", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Mizutsune_Icon.png"},
    {id: 23, name:"Almudron", species: "Brute Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Almudron_Icon.png"},
    {id: 24, name:"Goss Harag", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Goss_Harag_Icon.png"},
    {id: 25, name:"Tigrex", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Tigrex_Icon.png"},
    {id: 26, name:"Zinogre", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Zinogre_Icon.png"},
    {id: 27, name:"Diablos", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Diablos_Icon.png"},
    {id: 28, name:"Rathalos", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Rathalos_Icon.png"},
    {id: 29, name:"Nargacuga", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Nargacuga_Icon.png"},
    {id: 30, name:"Rakna-Kadaki", species: "Temnocerans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Rakna-Kadaki_Icon.png"},
    {id: 31, name:"Rajang", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Rajang_Icon.png"},
    {id: 32, name:"Jyuratodus", species: "Piscine Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Jyuratodus_Icon.png"},
    {id: 33, name:"Bazelgeuse", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Bazelgeuse_Icon.png"},
    {id: 34, name:"Kushala Daora", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Kushala_Daora_Icon.png"},
    {id: 35, name:"Teostra", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Teostra_Icon.png"},
    {id: 36, name:"Chameleos", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Chameleos_Icon.png"},
    {id: 37, name:"Crimson Glow Valstrax", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Crimson_Glow_Valstrax_Icon.png"},
    {id: 38, name:"Thunder Serpent Narwa", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Thunder_Serpent_Narwa_Icon.png"},
    {id: 39, name:"Wind Serpent Ibushi", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Wind_Serpent_Ibushi_Icon.png"},
    {id: 40, name:"Narwa the Allmother", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Narwa_the_Allmother_Icon.png"},
    {id: 41, name:"Apex Rathalos", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Rathalos_Icon.png"},
    {id: 42, name:"Apex Rathian", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Rathian_Icon.png"},
    {id: 43, name:"Apex Diablos", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Diablos_Icon.png"},
    {id: 44, name:"Apex Arzuros", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Arzuros_Icon.png"},
    {id: 45, name:"Apex Zinogre", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Zinogre_Icon.png"},
    {id: 46, name:"Apex Mizutsune", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Mizutsune_Icon.png"}
];

const baseSmallMonsters = [
    {id: 47, name:"Izuchi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Izuchi_Icon.png"},
    {id: 48, name:"Baggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Baggi_Icon.png"},
    {id: 49, name:"Wroggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Wroggi_Icon.png"},
    {id: 50, name:"Jaggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Jaggi_Icon.png"},
    {id: 51, name:"Jaggia", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Jaggia_Icon.png"},
    {id: 52, name:"Gajau", species: "Fish", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Gajau_Icon.png"},
    {id: 53, name:"Anteka", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Anteka_Icon.png"},
    {id: 54, name:"Kelbi", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Kelbi_Icon.png"},
    {id: 55, name:"Popo", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Popo_Icon.png"},
    {id: 56, name:"Rhenoplos", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Rhenoplos_Icon.png"},
    {id: 57, name:"Kestodon Male", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Kestodon_Male_Icon.png"},
    {id: 58, name:"Kestodon Female", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Kestodon_Female_Icon.png"},
    {id: 59, name:"Slagtoth", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Slagtoth_Icon.png"},
    {id: 60, name:"Melynx", species: "Lynians", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Melynx_Icon.png"},
    {id: 61, name:"Felyne", species: "Lynians", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Felyne_Icon.png"},
    {id: 62, name:"Altaroth", species: "Neopterons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Altaroth_Icon.png"},
    {id: 63, name:"Bnahabra", species: "Neopterons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Bnahabra_Icon.png"},
    {id: 64, name:"Rachnoid", species: "Temnocerans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Rachnoid_Icon.png"},
    {id: 65, name:"Zamite", species: "Amphibians", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Zamite_Icon.png"},
    {id: 66, name:"Bombadgy", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Bombadgy_Icon.png"},
    {id: 67, name:"Ludroth", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Ludroth_Icon.png"},
    {id: 68, name:"Delex", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Delex_Icon.png"},
    {id: 69, name:"Bullfango", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Bullfango_Icon.png"},
    {id: 70, name:"Jagras", species: "Fanged Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Jagras_Icon.png"},
    {id: 71, name:"Gargwa", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Gargwa_Icon.png"},
    {id: 72, name:"Remobra", species: "Snake Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Remobra_Icon.png"},
    {id: 73, name:"Uroktor", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Uroktor_Icon.png"}
];

const expansionSunbreakMonsters = [
    {name:"Daimyo Hermitaur", species:"Carapaceons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Daimyo_Hermitaur_Icon.png"},
    {name:"Blood Orange_Bishaten", species:"Fanged Beasts", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Blood_Orange_Bishaten_Icon.png"},
    {name:"Garangolm", species:"Fanged Beasts", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Garangolm_Icon.png"},
    {name:"Shogun Ceanataur", species:"Carapaceons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Shogun_Ceanataur_Icon.png"},
    {name:"Lunagaron", species:"Fanged Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Lunagaron_Icon.png"},
    {name:"Astalos", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Astalos_Icon.png"},
    {name:"Seregios", species:"Flying Wynerns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Seregios_Icon.png"},
    {name:"Magma Almudron", species:"Leviathans", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Magma_Almudron_Icon.png"},
    {name:"Gore Magala", species:"???", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Gore_Magala_Icon.png"},
    {name:"Espinas", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Espinas_Icon.png"},
    {name:"Pyre Rakna-Kadaki", species:"Temnocerans", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Pyre_Rakna-Kadaki_Icon.png"},
    {name:"Malzeno", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Malzeno_Icon.png"},
    {name:"Shagaru Magala", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Shagaru_Magala_Icon.png"},
    {name:"Gaismagorm", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Gaismagorm_Icon.png"},
    {name:"Scorned Magnamalo", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Scorned_Magnamalo_Icon.png"},
    {name:"Seething Bazelgeuse", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Seething_Bazelgeuse_Icon.png"},
    {name:"Silver Rathalos", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Silver_Rathalos_Icon.png"},
    {name:"Gold Rathian", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Gold_Rathian_Icon.png"},
    {name:"Lucent Nargacuga", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Lucent_Nargacuga_Icon.png"},
    {name:"Flaming Espinas", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Flaming_Espinas_Icon.png"},
    {name:"Violet Mizutsune", species:"Leviathans", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Violet_Mizutsune_Icon.png"},
    {name:"Risen Chameleos", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Chameleos_Icon.png"},
    {name:"Chaotic Gore Magala", species:"???", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Chaotic_Gore_Magala_Icon.png"},
    {name:"Risen Kushala Daora", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Kushala_Daora_Icon.png"},
    {name:"Risen Teostra", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Teostra_Icon.png"},
    {name:"Velkhana", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Velkhana_Icon.png"},
    {name:"Risen Crimson Glow Valstrax", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Crimson_Glow_Valstrax_Icon.png"},
    {name:"Amatsu", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Amatsu_Icon.png"},
    {name:"Risen Shagaru Magala", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Shagaru_Magala_Icon.png"},
    {name:"Primordial Malzeno", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Primordial_Malzeno_Icon.png"},
    {name:"Ceanataur", species:"Carapaceons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Ceanataur_Icon.png"},
    {name:"Gowngoat", species:"Herbivores", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Gowngoat_Icon.png"},
    {name:"Boggi", species:"Bird Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Boggi_Icon.png"},
    {name:"Hermitaur", species:"Carapaceons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Hermitaur_Icon.png"},
    {name:"Velociprey", species:"Bird Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Velociprey_Icon.png"}
];
const expansionLargeMonsters = [
    {name:"Daimyo Hermitaur", species:"Carapaceons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Daimyo_Hermitaur_Icon.png"},
    {name:"Blood Orange_Bishaten", species:"Fanged Beasts", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Blood_Orange_Bishaten_Icon.png"},
    {name:"Garangolm", species:"Fanged Beasts", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Garangolm_Icon.png"},
    {name:"Shogun Ceanataur", species:"Carapaceons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Shogun_Ceanataur_Icon.png"},
    {name:"Lunagaron", species:"Fanged Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Lunagaron_Icon.png"},
    {name:"Astalos", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Astalos_Icon.png"},
    {name:"Seregios", species:"Flying Wynerns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Seregios_Icon.png"},
    {name:"Magma Almudron", species:"Leviathans", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Magma_Almudron_Icon.png"},
    {name:"Gore Magala", species:"???", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Gore_Magala_Icon.png"},
    {name:"Espinas", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Espinas_Icon.png"},
    {name:"Pyre Rakna-Kadaki", species:"Temnocerans", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Pyre_Rakna-Kadaki_Icon.png"},
    {name:"Malzeno", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Malzeno_Icon.png"},
    {name:"Shagaru Magala", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Shagaru_Magala_Icon.png"},
    {name:"Gaismagorm", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Gaismagorm_Icon.png"},
    {name:"Scorned Magnamalo", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Scorned_Magnamalo_Icon.png"},
    {name:"Seething Bazelgeuse", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Seething_Bazelgeuse_Icon.png"},
    {name:"Silver Rathalos", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Silver_Rathalos_Icon.png"},
    {name:"Gold Rathian", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Gold_Rathian_Icon.png"},
    {name:"Lucent Nargacuga", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Lucent_Nargacuga_Icon.png"},
    {name:"Flaming Espinas", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Flaming_Espinas_Icon.png"},
    {name:"Violet Mizutsune", species:"Leviathans", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Violet_Mizutsune_Icon.png"},
    {name:"Risen Chameleos", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Chameleos_Icon.png"},
    {name:"Chaotic Gore Magala", species:"???", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Chaotic_Gore_Magala_Icon.png"},
    {name:"Risen Kushala Daora", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Kushala_Daora_Icon.png"},
    {name:"Risen Teostra", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Teostra_Icon.png"},
    {name:"Velkhana", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Velkhana_Icon.png"},
    {name:"Risen Crimson Glow Valstrax", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Crimson_Glow_Valstrax_Icon.png"},
    {name:"Amatsu", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Amatsu_Icon.png"},
    {name:"Risen Shagaru Magala", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Shagaru_Magala_Icon.png"},
    {name:"Primordial Malzeno", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Primordial_Malzeno_Icon.png"}
];
const expansionSmallMonsters = [
    {name:"Ceanataur", species:"Carapaceons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Ceanataur_Icon.png"},
    {name:"Gowngoat", species:"Herbivores", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Gowngoat_Icon.png"},
    {name:"Boggi", species:"Bird Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Boggi_Icon.png"},
    {name:"Hermitaur", species:"Carapaceons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Hermitaur_Icon.png"},
    {name:"Velociprey", species:"Bird Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Velociprey_Icon.png"}
];