const baseRiseMonsters = [
    {name:"Great Izuchi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Great_Izuchi_Icon.png"},
    {name:"Great Baggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Great_Baggi_Icon.png"},
    {name:"Kulu-Ya-Ku", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Kulu-Ya-Ku_Icon.png"},
    {name:"Great Wroggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Great_Wroggi_Icon.png"},
    {name:"Arzuros", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Arzuros_Icon.png"},
    {name:"Lagombi", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Lagombi_Icon.png"},
    {name:"Volvidon", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Volvidon_Icon.png"},
    {name:"Aknosom", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Aknosom_Icon.png"},
    {name:"Royal Ludroth", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Royal_Ludroth_Icon.png"},
    {name:"Barroth", species: "Brute Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Barroth_Icon.png"},
    {name:"Khezu", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Khezu_Icon.png"},
    {name:"Tetranadon", species: "Amphibians", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Tetranadon_Icon.png"},
    {name:"Bishaten", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Bishaten_Icon.png"},
    {name:"Pukei-Pukei", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Pukei-Pukei_Icon.png"},
    {name:"Basarios", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Basarios_Icon.png"},
    {name:"Somnacanth", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Somnacanth_Icon.png"},
    {name:"Rathian", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Rathian_Icon.png"},
    {name:"Barioth", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Barioth_Icon.png"},
    {name:"Tobi-Kadachi", species: "Fanged Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Tobi-Kadachi_Icon.png"},
    {name:"Magnamalo", species: "Brute Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Magnamalo_Icon.png"},
    {name:"Anjanath", species: "Brute Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Anjanath_Icon.png"},
    {name:"Mizutsune", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Mizutsune_Icon.png"},
    {name:"Almudron", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Almudron_Icon.png"},
    {name:"Goss Harag", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Goss_Harag_Icon.png"},
    {name:"Tigrex", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Tigrex_Icon.png"},
    {name:"Zinogre", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Zinogre_Icon.png"},
    {name:"Diablos", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Diablos_Icon.png"},
    {name:"Rathalos", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Rathalos_Icon.png"},
    {name:"Nargacuga", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Nargacuga_Icon.png"},
    {name:"Rakna-Kadaki", species: "Temnocerans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Rakna-Kadaki_Icon.png"},
    {name:"Rajang", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Rajang_Icon.png"},
    {name:"Jyuratodus", species: "Piscine Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Jyuratodus_Icon.png"},
    {name:"Bazelgeuse", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Bazelgeuse_Icon.png"},
    {name:"Kushala Daora", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Kushala_Daora_Icon.png"},
    {name:"Teostra", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Teostra_Icon.png"},
    {name:"Chameleos", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Chameleos_Icon.png"},
    {name:"Crimson Glow Valstrax", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Crimson_Glow_Valstrax_Icon.png"},
    {name:"Thunder Serpent Narwa", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Thunder_Serpent_Narwa_Icon.png"},
    {name:"Wind Serpent Ibushi", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Wind_Serpent_Ibushi_Icon.png"},
    {name:"Narwa the Allmother", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Narwa_the_Allmother_Icon.png"},
    {name:"Apex Rathalos", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Rathalos_Icon.png"},
    {name:"Apex Rathian", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Rathian_Icon.png"},
    {name:"Apex Diablos", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Diablos_Icon.png"},
    {name:"Apex Arzuros", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Arzuros_Icon.png"},
    {name:"Apex Zinogre", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Zinogre_Icon.png"},
    {name:"Apex Mizutsune", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Mizutsune_Icon.png"},

    {name:"Izuchi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Izuchi_Icon.png"},
    {name:"Baggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Baggi_Icon.png"},
    {name:"Wroggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Wroggi_Icon.png"},
    {name:"Jaggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Jaggi_Icon.png"},
    {name:"Jaggia", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Jaggia_Icon.png"},
    {name:"Gajau", species: "Fish", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Gajau_Icon.png"},
    {name:"Anteka", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Anteka_Icon.png"},
    {name:"Kelbi", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Kelbi_Icon.png"},
    {name:"Popo", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Popo_Icon.png"},
    {name:"Rhenoplos", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Rhenoplos_Icon.png"},
    {name:"Kestodon Male", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Kestodon_Male_Icon.png"},
    {name:"Kestodon Female", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Kestodon_Female_Icon.png"},
    {name:"Slagtoth", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Slagtoth_Icon.png"},
    {name:"Melynx", species: "Lynians", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Melynx_Icon.png"},
    {name:"Felyne", species: "Lynians", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Felyne_Icon.png"},
    {name:"Altaroth", species: "Neopterons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Altaroth_Icon.png"},
    {name:"Bnahabra", species: "Neopterons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Bnahabra_Icon.png"},
    {name:"Rachnoid", species: "Temnocerans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Rachnoid_Icon.png"},
    {name:"Zamite", species: "Amphibians", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Zamite_Icon.png"},
    {name:"Bombadgy", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Bombadgy_Icon.png"},
    {name:"Ludroth", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Ludroth_Icon.png"},
    {name:"Delex", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Delex_Icon.png"},
    {name:"Bullfango", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Bullfango_Icon.png"},
    {name:"Jagras", species: "Fanged Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Jagras_Icon.png"},
    {name:"Gargwa", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Gargwa_Icon.png"},
    {name:"Remobra", species: "Snake Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Remobra_Icon.png"},
    {name:"Uroktor", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Uroktor_Icon.png"}
];

const baseLargeMonsters = [
    {name:"Great Izuchi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Great_Izuchi_Icon.png"},
    {name:"Great Baggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Great_Baggi_Icon.png"},
    {name:"Kulu-Ya-Ku", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Kulu-Ya-Ku_Icon.png"},
    {name:"Great Wroggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Great_Wroggi_Icon.png"},
    {name:"Arzuros", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Arzuros_Icon.png"},
    {name:"Lagombi", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Lagombi_Icon.png"},
    {name:"Volvidon", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Volvidon_Icon.png"},
    {name:"Aknosom", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Aknosom_Icon.png"},
    {name:"Royal Ludroth", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Royal_Ludroth_Icon.png"},
    {name:"Barroth", species: "Brute Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Barroth_Icon.png"},
    {name:"Khezu", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Khezu_Icon.png"},
    {name:"Tetranadon", species: "Amphibians", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Tetranadon_Icon.png"},
    {name:"Bishaten", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Bishaten_Icon.png"},
    {name:"Pukei-Pukei", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Pukei-Pukei_Icon.png"},
    {name:"Basarios", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Basarios_Icon.png"},
    {name:"Somnacanth", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Somnacanth_Icon.png"},
    {name:"Rathian", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Rathian_Icon.png"},
    {name:"Barioth", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Barioth_Icon.png"},
    {name:"Tobi-Kadachi", species: "Fanged Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Tobi-Kadachi_Icon.png"},
    {name:"Magnamalo", species: "Fanged Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Magnamalo_Icon.png"},
    {name:"Anjanath", species: "Brute Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Anjanath_Icon.png"},
    {name:"Mizutsune", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Mizutsune_Icon.png"},
    {name:"Almudron", species: "Brute Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Almudron_Icon.png"},
    {name:"Goss Harag", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Goss_Harag_Icon.png"},
    {name:"Tigrex", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Tigrex_Icon.png"},
    {name:"Zinogre", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Zinogre_Icon.png"},
    {name:"Diablos", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Diablos_Icon.png"},
    {name:"Rathalos", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Rathalos_Icon.png"},
    {name:"Nargacuga", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Nargacuga_Icon.png"},
    {name:"Rakna-Kadaki", species: "Temnocerans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Rakna-Kadaki_Icon.png"},
    {name:"Rajang", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Rajang_Icon.png"},
    {name:"Jyuratodus", species: "Piscine Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Jyuratodus_Icon.png"},
    {name:"Bazelgeuse", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Bazelgeuse_Icon.png"},
    {name:"Kushala Daora", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Kushala_Daora_Icon.png"},
    {name:"Teostra", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Teostra_Icon.png"},
    {name:"Chameleos", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Chameleos_Icon.png"},
    {name:"Crimson Glow Valstrax", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Crimson_Glow_Valstrax_Icon.png"},
    {name:"Thunder Serpent Narwa", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Thunder_Serpent_Narwa_Icon.png"},
    {name:"Wind Serpent Ibushi", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Wind_Serpent_Ibushi_Icon.png"},
    {name:"Narwa the Allmother", species: "Elder Dragons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Narwa_the_Allmother_Icon.png"},
    {name:"Apex Rathalos", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Rathalos_Icon.png"},
    {name:"Apex Rathian", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Rathian_Icon.png"},
    {name:"Apex Diablos", species: "Flying Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Diablos_Icon.png"},
    {name:"Apex Arzuros", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Arzuros_Icon.png"},
    {name:"Apex Zinogre", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Zinogre_Icon.png"},
    {name:"Apex Mizutsune", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/LargeMonsters-Icon/MHRS-Apex_Mizutsune_Icon.png"}
];

const baseSmallMonsters = [
    {name:"Izuchi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Izuchi_Icon.png"},
    {name:"Baggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Baggi_Icon.png"},
    {name:"Wroggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Wroggi_Icon.png"},
    {name:"Jaggi", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Jaggi_Icon.png"},
    {name:"Jaggia", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Jaggia_Icon.png"},
    {name:"Gajau", species: "Fish", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Gajau_Icon.png"},
    {name:"Anteka", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Anteka_Icon.png"},
    {name:"Kelbi", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Kelbi_Icon.png"},
    {name:"Popo", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Popo_Icon.png"},
    {name:"Rhenoplos", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Rhenoplos_Icon.png"},
    {name:"Kestodon Male", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Kestodon_Male_Icon.png"},
    {name:"Kestodon Female", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Kestodon_Female_Icon.png"},
    {name:"Slagtoth", species: "Herbivores", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Slagtoth_Icon.png"},
    {name:"Melynx", species: "Lynians", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Melynx_Icon.png"},
    {name:"Felyne", species: "Lynians", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Felyne_Icon.png"},
    {name:"Altaroth", species: "Neopterons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Altaroth_Icon.png"},
    {name:"Bnahabra", species: "Neopterons", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Bnahabra_Icon.png"},
    {name:"Rachnoid", species: "Temnocerans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Rachnoid_Icon.png"},
    {name:"Zamite", species: "Amphibians", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Zamite_Icon.png"},
    {name:"Bombadgy", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Bombadgy_Icon.png"},
    {name:"Ludroth", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Ludroth_Icon.png"},
    {name:"Delex", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Delex_Icon.png"},
    {name:"Bullfango", species: "Fanged Beasts", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Bullfango_Icon.png"},
    {name:"Jagras", species: "Fanged Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Jagras_Icon.png"},
    {name:"Gargwa", species: "Bird Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Gargwa_Icon.png"},
    {name:"Remobra", species: "Snake Wyverns", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Remobra_Icon.png"},
    {name:"Uroktor", species: "Leviathans", image: "../../MH-Images/MonsterHunter-Images/MonsterHunterRise/SmallMonsters-Icon/MHRS-Uroktor_Icon.png"}
];

const expansionSunbreakMonsters = [
    {name:"Daimyo Hermitaur", species:"Carapaceons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Daimyo_Hermitaur_Icon.png"},
    {name:"Blood Orange_Bishaten", species:"Fanged Beasts", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Blood_Orange_Bishaten_Icon.png"},
    {name:"Garangolm", species:"Fanged Beasts", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Garangolm_Icon.png"},
    {name:"Shogun Ceanataur", species:"Carapaceons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Shogun_Ceanataur_Icon.png"},
    {name:"Lunagaron", species:"Fanged Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Lunagaron_Icon.png"},
    {name:"Astalos", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Astalos_Icon.png"},
    {name:"Seregios", species:"Flying Wynerns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Seregios_Icon.png"},
    {name:"Magma Almudron", species:"Leviathans", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Magma_Almudron_Icon.png"},
    {name:"Gore Magala", species:"???", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Gore_Magala_Icon.png"},
    {name:"Espinas", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Espinas_Icon.png"},
    {name:"Pyre Rakna-Kadaki", species:"Temnocerans", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Pyre_Rakna-Kadaki_Icon.png"},
    {name:"Malzeno", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Malzeno_Icon.png"},
    {name:"Shagaru Magala", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Shagaru_Magala_Icon.png"},
    {name:"Gaismagorm", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Gaismagorm_Icon.png"},
    {name:"Scorned Magnamalo", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Scorned_Magnamalo_Icon.png"},
    {name:"Seething Bazelgeuse", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Seething_Bazelgeuse_Icon.png"},
    {name:"Silver Rathalos", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Silver_Rathalos_Icon.png"},
    {name:"Gold Rathian", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Gold_Rathian_Icon.png"},
    {name:"Lucent Nargacuga", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Lucent_Nargacuga_Icon.png"},
    {name:"Flaming Espinas", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Flaming_Espinas_Icon.png"},
    {name:"Violet Mizutsune", species:"Leviathans", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Violet_Mizutsune_Icon.png"},
    {name:"Risen Chameleos", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Chameleos_Icon.png"},
    {name:"Chaotic Gore Magala", species:"???", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Chaotic_Gore_Magala_Icon.png"},
    {name:"Risen Kushala Daora", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Kushala_Daora_Icon.png"},
    {name:"Risen Teostra", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Teostra_Icon.png"},
    {name:"Velkhana", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Velkhana_Icon.png"},
    {name:"Risen Crimson Glow Valstrax", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Crimson_Glow_Valstrax_Icon.png"},
    {name:"Amatsu", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Amatsu_Icon.png"},
    {name:"Risen Shagaru Magala", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Shagaru_Magala_Icon.png"},
    {name:"Primordial Malzeno", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Primordial_Malzeno_Icon.png"},
    {name:"Ceanataur", species:"Carapaceons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Ceanataur_Icon.png"},
    {name:"Gowngoat", species:"Herbivores", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Gowngoat_Icon.png"},
    {name:"Boggi", species:"Bird Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Boggi_Icon.png"},
    {name:"Hermitaur", species:"Carapaceons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Hermitaur_Icon.png"},
    {name:"Velociprey", species:"Bird Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Velociprey_Icon.png"}
];
const expansionLargeMonsters = [
    {name:"Daimyo Hermitaur", species:"Carapaceons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Daimyo_Hermitaur_Icon.png"},
    {name:"Blood Orange_Bishaten", species:"Fanged Beasts", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Blood_Orange_Bishaten_Icon.png"},
    {name:"Garangolm", species:"Fanged Beasts", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Garangolm_Icon.png"},
    {name:"Shogun Ceanataur", species:"Carapaceons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Shogun_Ceanataur_Icon.png"},
    {name:"Lunagaron", species:"Fanged Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Lunagaron_Icon.png"},
    {name:"Astalos", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Astalos_Icon.png"},
    {name:"Seregios", species:"Flying Wynerns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Seregios_Icon.png"},
    {name:"Magma Almudron", species:"Leviathans", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Magma_Almudron_Icon.png"},
    {name:"Gore Magala", species:"???", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Gore_Magala_Icon.png"},
    {name:"Espinas", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Espinas_Icon.png"},
    {name:"Pyre Rakna-Kadaki", species:"Temnocerans", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Pyre_Rakna-Kadaki_Icon.png"},
    {name:"Malzeno", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Malzeno_Icon.png"},
    {name:"Shagaru Magala", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Shagaru_Magala_Icon.png"},
    {name:"Gaismagorm", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Gaismagorm_Icon.png"},
    {name:"Scorned Magnamalo", species:"Brute Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Scorned_Magnamalo_Icon.png"},
    {name:"Seething Bazelgeuse", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Seething_Bazelgeuse_Icon.png"},
    {name:"Silver Rathalos", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Silver_Rathalos_Icon.png"},
    {name:"Gold Rathian", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Gold_Rathian_Icon.png"},
    {name:"Lucent Nargacuga", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Lucent_Nargacuga_Icon.png"},
    {name:"Flaming Espinas", species:"Flying Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Flaming_Espinas_Icon.png"},
    {name:"Violet Mizutsune", species:"Leviathans", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Violet_Mizutsune_Icon.png"},
    {name:"Risen Chameleos", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Chameleos_Icon.png"},
    {name:"Chaotic Gore Magala", species:"???", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Chaotic_Gore_Magala_Icon.png"},
    {name:"Risen Kushala Daora", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Kushala_Daora_Icon.png"},
    {name:"Risen Teostra", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Teostra_Icon.png"},
    {name:"Velkhana", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Velkhana_Icon.png"},
    {name:"Risen Crimson Glow Valstrax", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Crimson_Glow_Valstrax_Icon.png"},
    {name:"Amatsu", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Amatsu_Icon.png"},
    {name:"Risen Shagaru Magala", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Risen_Shagaru_Magala_Icon.png"},
    {name:"Primordial Malzeno", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Primordial_Malzeno_Icon.png"}
];
const expansionSmallMonsters = [
    {name:"Primordial Malzeno", species:"Elder Dragons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/LargeMonsters-Icons/MHRS-Primordial_Malzeno_Icon.png"},
    {name:"Ceanataur", species:"Carapaceons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Ceanataur_Icon.png"},
    {name:"Gowngoat", species:"Herbivores", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Gowngoat_Icon.png"},
    {name:"Boggi", species:"Bird Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Boggi_Icon.png"},
    {name:"Hermitaur", species:"Carapaceons", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Hermitaur_Icon.png"},
    {name:"Velociprey", species:"Bird Wyverns", rank:"Master-Rank", image:"../../MH-Images/MonsterHunter-Images/MonsterHunterRise-Sunbreak/SmallMonsters-Icons/MHRS-Velociprey_Icon.png"}
];