NEXT_PUBLIC_SUPABASE_URL= "https://raclkiumgbtqlvwmpvqt.supabase.co"
NEXT_PUBLIC_SUPABASE_PUBLICHABLE_KEY="sb_publishable_2Tq44eDe2qecfUdCFUdKAQ_WE03ukEf"

const supabaseClient =supabase.creatClient(NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_PUBLICHABLE_KEY);